@host = https://localhost:7090
@sqliteSourceKey = sample-employees-db
@sqlServerSourceKey = p_sqlserver
@cosmosSourceKey = p_cosmos
# SQL Server: DataQL.ExampleApi/docker/.env.example
# Cosmos: DataQL.ExampleApi/docker-cosmos/.env.example
###
GET {{host}}/
Accept: application/json
###
GET {{host}}/dataql/meta/openapi.json
Accept: application/json
###
GET {{host}}/dataql/meta/sources
Accept: application/json
###
GET {{host}}/dataql/meta/sources/{{sqliteSourceKey}}/tables
Accept: application/json
###
GET {{host}}/dataql/meta/sources/{{sqliteSourceKey}}/tables/Employees/schema
Accept: application/json
###
POST {{host}}/dataql/query/{{sqliteSourceKey}}/main.Employees
Content-Type: application/json
Accept: application/json

{
  "select": ["Name", "Id"],
  "where": {
    "Age": {
      "$gte": 21
    }
  },
  "order": [
    {
      "field": "Age",
      "direction": "desc"
    }
  ],
  "limit": 2,
  "includeCount": true
}
###
POST {{host}}/employees/query/manual/main.Employees
Content-Type: application/json
Accept: application/json

{
  "where": {
    "$and": [
      {
        "IsActive": true
      },
      {
        "Department": "Engineering"
      }
    ]
  },
  "order": [
    {
      "field": "City",
      "direction": "asc"
    }
  ],
  "includeCount": true
}
###
POST {{host}}/dataql/query/{{sqlServerSourceKey}}/dbo.Employees
Content-Type: application/json
Accept: application/json

{
  "select": ["Name", "Id"],
  "where": {
    "Age": {
      "$gte": 21
    }
  },
  "order": [
    {
      "field": "Age",
      "direction": "desc"
    }
  ],
  "limit": 2,
  "includeCount": true
}
###
POST {{host}}/employees/query/manual/sqlserver/dbo.Employees
Content-Type: application/json
Accept: application/json

{
  "where": {
    "Department": "Engineering"
  },
  "order": [
    {
      "field": "City",
      "direction": "asc"
    }
  ],
  "includeCount": true
}
###
GET {{host}}/dataql/meta/sources/{{cosmosSourceKey}}/tables
Accept: application/json
###
POST {{host}}/dataql/query/{{cosmosSourceKey}}/Employees
Content-Type: application/json
Accept: application/json

{
  "select": ["Name", "Id"],
  "where": {
    "Age": {
      "$gte": 21
    }
  },
  "order": [
    {
      "field": "Age",
      "direction": "desc"
    }
  ],
  "limit": 2
}
