<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\DataQL.AspNetCore\DataQL.AspNetCore.csproj" />
    <ProjectReference Include="..\DataQL.Sqlite\DataQL.Sqlite.csproj" />
    <ProjectReference Include="..\DataQL.SqlServer\DataQL.SqlServer.csproj" />
    <ProjectReference Include="..\DataQL.Cosmos\DataQL.Cosmos.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.17" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
